# Generated by Django 6.0.6 on 2026-07-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('caption', models.CharField(max_length=256)),
                ('desc', models.TextField(blank=True, max_length=2048)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('desc', models.TextField(blank=True, max_length=2048)),
                ('slug', models.SlugField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
                ('posts', models.ManyToManyField(related_name='galleries', to='portfolio.gallerypost')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'galleries',
            },
        ),
    ]
