# Generated by Django 6.0.6 on 2026-08-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
