# Generated by Django 6.0.6 on 2026-07-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactformresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='hidden',
        ),
    ]
