# Generated by Django 6.1.1 on 2026-09-07 19:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_aboutpage_what_is_llandv_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='cta_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='headshot_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='what_is_llandv_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='where_is_llandv_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='who_is_llandv_text',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
