# Generated by Django 6.0.6 on 2026-07-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_gallery_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='portfolio.gallerypost'),
        ),
    ]
