# Generated by Django 6.1.1 on 2026-09-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_galleryindexpage_gallerypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
