# Generated by Django 6.1.1 on 2026-09-12 21:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_navigationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='body',
            field=wagtail.fields.StreamField([('images', 1), ('description', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
    ]
